---
- name: Recargar systemd
  systemd:
    daemon_reload: yes

- name: Habilitar servicio contenedor
  systemd:
    name: "container-{{ container_name }}.service"
    enabled: true
    state: started